apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30080
